name: Esegui Script Python Periodicamente

on:
  schedule:
    - cron: '0 0 * * *'  # Esegui ogni giorno all'1:00 AM UTC, puoi personalizzare la cron syntax

jobs:
  esegui_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configura Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.5  # Sostituisci '3.x' con la versione di Python necessaria

    - name: Installa Dipendenze
      run: |
        python3 -m pip install --upgrade pip
        pip3 install anvil-uplink
        pip3 installfirebase-admin
        pip3 install cloudinary  # Sostituisci con il nome del tuo file requirements.txt se presente

    - name: Esegui Script Python
      run: python server.py  # Sostituisci 'nome_del_tuo_script.py' con il tuo script Python
